runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'unisundevdb'
  DATABASE_USER: 'urquhmotrdhwqg'
  DATABASE_PASSWORD: 'efad4bb2169e67ddaa17c21aba5c76efc6a9daa6a06310949eba9a006bf258da'
  INSTANCE_CONNECTION_NAME: 'unisun-345117:asia-southeast1:unisun'

beta_settings:
  cloud_sql_instances: 'unisun-345117:asia-southeast1:unisun'